# Generated by Django 5.2.7 on 2025-10-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_release_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('video_url', models.URLField()),
                ('category', models.CharField(default='General', max_length=100)),
                ('release_year', models.IntegerField(default=2025)),
            ],
        ),
    ]
