# Generated by Django 5.2.7 on 2025-10-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_series'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Series',
        ),
    ]
